# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: TianLang Hacker # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: TianLang Hacker # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: YYYYå¹´MMæœˆDDæ—¥ dddd # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 10 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: é¦–é¡µ # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: æ‰€æœ‰blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        
        - id: Linux
          text: Linux
          href: /blog/category/Linux
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        
        - id: android
          text: Android
          href: /blog/category/Android
          svg: "material-symbols:deployed-code-outline"
          target: _self
        
        - id: nas
          text: NAS
          href: /blog/category/NAS
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: å‹é“¾
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: EveSunMaple # ç”¨æˆ·å
  site: "https://frosti.saroprock.com" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /image/TianLang-Hacker.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://github.com/TianLang-Hacker"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/348006102"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.youtube.com/@tianlanghacker4630"
        ariaLabel: YouTube
        title: YouTube
        svg: "ri:youtube-line"
      - href: "https://qm.qq.com/q/8HvoVyyuE8"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line"
      - href: "https://t.me/+LCCpqJLBpWtlYjc1"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"
  footer:
    social:
      - href: "https://github.com/TianLang-Hacker"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/348006102"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://www.youtube.com/@tianlanghacker4630"
        ariaLabel: YouTube
        title: YouTube
        svg: "ri:youtube-line"
      - href: "https://qm.qq.com/q/8HvoVyyuE8"
        ariaLabel: QQ
        title: QQ
        svg: "ri:qq-line"
      - href: "https://t.me/+LCCpqJLBpWtlYjc1"
        ariaLabel: Telegram
        title: Telegram
        svg: "ri:telegram-line"
